# generated by vscext-fetcher Version {versionBranch = [0,1,0,0], versionTags = []}
{ vscode-utils }: {
  mike-lischke.vscode-antlr4 = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-antlr4";
    publisher = "mike-lischke";
    version = "2.3.1";
    sha256 = "1sbkdg2bp0jgihmib36zfcvkcjgh1j3chphhs5ly7754mla09x7a";
  };
  mshr-h.VerilogHDL = vscode-utils.extensionFromVscodeMarketplace {
    name = "VerilogHDL";
    publisher = "mshr-h";
    version = "1.11.11";
    sha256 = "0jpi791b5ka1jsks32k9fi9qdga08xjf257is9y3vav4a1cp2ck3";
  };
  teabyii.ayu = vscode-utils.extensionFromVscodeMarketplace {
    name = "ayu";
    publisher = "teabyii";
    version = "1.0.5";
    sha256 = "1visv44mizfvsysrdby1vrncv1g3qmf45rhjijmbyak2d60nm0gq";
  };
  ziglang.vscode-zig = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-zig";
    publisher = "ziglang";
    version = "0.4.2";
    sha256 = "0k56ildn16sd24fcpabgxrn1r1arpjjbsra9whg4l73rnrb435nv";
  };
  fwcd.kotlin = vscode-utils.extensionFromVscodeMarketplace {
    name = "kotlin";
    publisher = "fwcd";
    version = "0.2.31";
    sha256 = "1yngrbqndb7jccmakpjv98y8amffvk2zbj3dhz0khdxz6ym18vb3";
  };
}
