# generated by vscext-fetcher Version {versionBranch = [0,1,0,0], versionTags = []}
{ vscode-utils }: {
  maximedenes.vscoq = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscoq";
    publisher = "maximedenes";
    version = "0.3.6";
    sha256 = "1sailpizg7zvncggdma9dyxdnga8jya1a2vswwij1rzd9il04j3g";
  };
  mike-lischke.vscode-antlr4 = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-antlr4";
    publisher = "mike-lischke";
    version = "2.3.1";
    sha256 = "1sbkdg2bp0jgihmib36zfcvkcjgh1j3chphhs5ly7754mla09x7a";
  };
}