# generated by vscext-fetcher Version {versionBranch = [0,1,0,0], versionTags = []}
{ vscode-utils }: {
  maximedenes.vscoq = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscoq";
    publisher = "maximedenes";
    version = "0.3.8";
    sha256 = "12qyvc0d1m0i5mxmjp1swq7sd6ch6yi9v0f14hz64lig3clgjmfh";
  };
  mike-lischke.vscode-antlr4 = vscode-utils.extensionFromVscodeMarketplace {
    name = "vscode-antlr4";
    publisher = "mike-lischke";
    version = "2.3.1";
    sha256 = "1sbkdg2bp0jgihmib36zfcvkcjgh1j3chphhs5ly7754mla09x7a";
  };
  mshr-h.VerilogHDL = vscode-utils.extensionFromVscodeMarketplace {
    name = "VerilogHDL";
    publisher = "mshr-h";
    version = "1.11.4";
    sha256 = "0glfzz3cnj37ip4qn1va7nykly8dlfkmzg6bpw3lq8knldwk95p0";
  };
  teabyii.ayu = vscode-utils.extensionFromVscodeMarketplace {
    name = "ayu";
    publisher = "teabyii";
    version = "1.0.5";
    sha256 = "1visv44mizfvsysrdby1vrncv1g3qmf45rhjijmbyak2d60nm0gq";
  };
  tamasfe.even-better-toml = vscode-utils.extensionFromVscodeMarketplace {
    name = "even-better-toml";
    publisher = "tamasfe";
    version = "0.19.0";
    sha256 = "0xfnprgbafy7sfdqwdw92lr8k3h3fbylvhq1swgv31akndm9191j";
  };
}